### ISSUE TITLE
GUI displays directory name as project name

### ISSUE THREAD

**Issue by samshipengs** [dessa-research/Image-segmentation-tutorial#1]
From section `Running a Hyperparameter Search`, after running `python hyperparameter_search.py` in directory `code`, there is a new project named `code`(the directory where the command was run) got created, and it contains a job that finished running in a few seconds. All the actual jobs were sent to the correct project and running.

![image](https://user-images.githubusercontent.com/4667249/66339693-a72d7200-e911-11e9-86ca-e8120c6ebfcd.png)

![Screen Shot 2019-10-07 at 2 49 37 PM](https://user-images.githubusercontent.com/4667249/66339850-fffd0a80-e911-11e9-9cac-36bf10eeb0c7.png)

![Screen Shot 2019-10-07 at 2 51 28 PM](https://user-images.githubusercontent.com/4667249/66339865-04292800-e912-11e9-9500-acef2faab6e2.png)
(also somehow there is a failed job but didnt display any error message in the log)

**Comment by mohammedri** [comment]
Hey @samshipengs ! Thanks for pointing this out. We will have a fix for this shortly =)
